#cloud-config
ssh_authorized_keys:
  - ${custom_ssh}

system_info:
 default_user:
  name: ${username}

package_upgrade: true
timezone: UTC
locale: "en_US.UTF-8"

write_files:
  - path: /etc/docker/daemon.json
    owner: "root:root"
    content: |
     {
       "log-driver": "json-file",
       "log-opts": {
         "max-size": "10m",
         "max-file": "3",
         "labels": "production_status",
         "env": "os,customer"
       }
     }

runcmd:
  - apt-get update
  # Configure automatic updates
  - echo unattended-upgrades unattended-upgrades/enable_auto_updates boolean true | debconf-set-selections
  - apt-get -y install unattended-upgrades
  # Install Docker
  - apt-get install -y apt-transport-https ca-certificates curl software-properties-common
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - apt-get update
# To install a specific Docker version use:
#  - apt-get install -y docker-ce=5:19.03.11~3-0~ubuntu-focal docker-ce-cli=5:19.03.11~3-0~ubuntu-focal containerd.io
# otherwise:
  - curl -sSL https://get.docker.com/ | sh
  - groupadd docker
# ---
  - usermod -aG docker $USER
  - newgrp docker
  - systemctl enable docker
  - ${registration_command}
